### ISSUE TITLE
Error report for Mockswitch 1.52.0

### ISSUE THREAD

**Issue by dsadhanala** [mockswitch/support#2]
Error:
```UnhandledRejection TypeError: Cannot read properties of undefined (reading 'svcCode')
    at /Applications/Mockswitch.app/Contents/Resources/app.asar/dist/server.js:1:16655
    at e.exports (/Applications/Mockswitch.app/Contents/Resources/app.asar/dist/server.js:1:17108)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
OS: macOS 10.16

**Comment by dsadhanala** [comment]
{
 "$schema": "http://json-schema.org/draft-04/schema#",
 "description": "",
 "type": "object",
 "properties": {
  "success": {
   "type": "boolean"
  }
 },
 "required": [
  "success"
 ]
}

**Comment by dsadhanala** [comment]
[mockswitch_folder.zip](https://github.com/mockswitch/support/files/7272595/mockswitch_folder.zip)
PFA
